# Generated by Django 4.2.1 on 2023-05-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('planeModel', models.CharField(max_length=100)),
                ('numberOfRows', models.IntegerField()),
                ('seatsPerRow', models.IntegerField()),
                ('departureTime', models.DateTimeField()),
                ('departureDate', models.DateField()),
                ('arrivalTime', models.DateTimeField()),
                ('departureAirport', models.CharField(max_length=5)),
                ('destinationAirport', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passengerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('passportNumber', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seatNumber', models.IntegerField()),
                ('seatPrice', models.IntegerField()),
                ('seatTaken', models.BooleanField(default=False)),
                ('flightId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('holdLuggage', models.BooleanField(default=False)),
                ('paymentConfirmed', models.BooleanField(default=False)),
                ('passengerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger')),
                ('seatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.seat')),
            ],
        ),
    ]
